name: lint

on:
  push:
    branches: [ master, "[0-9]+.x" ]
  pull_request:
    branches: [ master, "[0-9]+.x" ]

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: composer-${{ runner.os }}-pint-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Pint (test mode)
        run: vendor/bin/pint --test

  composer-validate:
    name: composer validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict
